export default {
  AUTH: "AUTH",
  TOKEN: "TOKEN",
  USER: "USER",
  MOVIE_LIST: "MOVIE_LIST",
  CURRENT_PAGE: "CURRENT_PAGE",
  TOTAL_PAGES: "TOTAL_PAGES",
  TOTAL_MOVIES: "TOTAL_MOVIES",
  MOVIE_DETAIL: "MOVIE_DETAIL",
};
